organizationalunit = "Infra"
policyname         = "spokehubtagpolicy"
bucket             = "awsterraformspokehubsdev"
email              = "prasad.dursheti@gmail.com"
accountname        = "netrwork-dev"
region             = "us-east-1"
