location       = "eastus"
clientsecret   = ""
subscriptionid = ""
tenantid       = ""
clientid       = ""
parentgroup    = "/providers/Microsoft.Management/managementGroups/scopehub"
role           = "Management Group Contributor"